In [3]:
import numpy as np
from scipy.stats import uniform, randint
from sklearn.datasets import load_breast_cancer , load_diabetes,load_wine
from sklearn.metrics import accuracy_score,confusion_matrix,mean_squared_error
from sklearn.model_selection import cross_val_score,GridSearchCV,KFold,RandomizedSearchCV,train_test_split
import xgboost as xgb


In [15]:
def display_scores(scores):
    print("Scores: {0} \Mean :{1:3f}\nStd:{2:3}".format(scores,np.mean(scores),np.std(scores)))

In [6]:
diabetes=load_diabetes()
X=diabetes.data
y=diabetes.target
print(X[:5])
print(y[:5])

[[ 0.03807591  0.05068012  0.06169621  0.02187235 -0.0442235  -0.03482076
  -0.04340085 -0.00259226  0.01990842 -0.01764613]
 [-0.00188202 -0.04464164 -0.05147406 -0.02632783 -0.00844872 -0.01916334
   0.07441156 -0.03949338 -0.06832974 -0.09220405]
 [ 0.08529891  0.05068012  0.04445121 -0.00567061 -0.04559945 -0.03419447
  -0.03235593 -0.00259226  0.00286377 -0.02593034]
 [-0.08906294 -0.04464164 -0.01159501 -0.03665645  0.01219057  0.02499059
  -0.03603757  0.03430886  0.02269202 -0.00936191]
 [ 0.00538306 -0.04464164 -0.03638469  0.02187235  0.00393485  0.01559614
   0.00814208 -0.00259226 -0.03199144 -0.04664087]]
[151.  75. 141. 206. 135.]


In [10]:
xgb_model=xgb.XGBRegressor(objective="reg:squarederror",random_state=10)
train_X,test_X,train_y,test_y=train_test_split(X,y,random_state=10)
xgb_model.fit(train_X,train_y)
y_pred=xgb_model.predict(test_X)
mse=mean_squared_error(test_y,y_pred)
print("============")
print("RMSE:",np.sqrt(mse))

RMSE: 62.66498953382524


XGBClassifier

In [11]:
cancer=load_breast_cancer()
X=cancer.data
y=cancer.target
train_X,test_X,train_y,test_y=train_test_split(X,y,random_state=0)
xgb_model=xgb.XGBClassifier(objective="binary:logistic",random_state=42)
xgb_model.fit(train_X,train_y)
y_pred=xgb_model.predict(test_X)
print(confusion_matrix(test_y,y_pred))
print(accuracy_score(test_y,y_pred))


[[52  1]
 [ 1 89]]
0.986013986013986


In [13]:
wine=load_wine()
X=wine.data
y=wine.target
train_X,test_X,train_y,test_y=train_test_split(X,y,random_state=0)
xgb_model=xgb.XGBClassifier(objective="multi:softprob",random_state=42)
xgb_model.fit(train_X,train_y)
y_pred=xgb_model.predict(test_X)
print(confusion_matrix(test_y,y_pred))
print(accuracy_score(test_y,y_pred))

[[16  0  0]
 [ 1 19  1]
 [ 0  0  8]]
0.9555555555555556


In [16]:
diabetes = load_diabetes()

X = diabetes.data
y = diabetes.target

kfold = KFold(n_splits=5, shuffle=True, random_state=42)

scores = []

for train_index, test_index in kfold.split(X):   
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]

    xgb_model = xgb.XGBRegressor(objective="reg:squarederror")
    xgb_model.fit(X_train, y_train)
    
    y_pred = xgb_model.predict(X_test)
    
    scores.append(mean_squared_error(y_test, y_pred))
    
display_scores(np.sqrt(scores))


Scores: [63.94113147 61.42459229 67.48347369 69.49735072 59.90352078] \Mean :64.450014
Std:3.598894947685029


In [20]:
xgb_model = xgb.XGBRegressor(objective="reg:squarederror", random_state=42)
scores=cross_val_score(xgb_model,X,y,scoring="neg_mean_squared_error",cv=5)
display_scores(np.sqrt(-scores))

Scores: [62.80101897 65.82933092 62.19849144 66.40701358 67.29879568] \Mean :64.906930
Std:2.0294135275879284
