In [3]:
import seaborn as sns
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import svm,datasets


In [4]:
irsidata=sns.load_dataset('iris')
irsidata.head()


sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [6]:
X=irsidata.drop('species',axis=1)
y=irsidata['species']

In [10]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.20)
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

from sklearn.decomposition import PCA
pca=PCA(n_components=1)
X_train=pca.fit_transform(X_train)
X_test=pca.transform(X_test)

print(X_train[:5])

[[ 2.44102902]
 [ 1.95028942]
 [-2.29775148]
 [-0.3618507 ]
 [ 0.70033107]]


In [11]:
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier(max_depth=2,random_state=0,n_estimators=10)

In [12]:
classifier.fit(X_train,y_train)

RandomForestClassifier(max_depth=2, n_estimators=10, random_state=0)

In [14]:
y_pred=classifier.predict(X_test)
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
cm=confusion_matrix(y_test,y_pred)
print(cm)
print('Accuracy ',accuracy_score(y_test,y_pred))

[[ 8  0  0]
 [ 0  9  2]
 [ 0  1 10]]
Accuracy  0.9
